### ISSUE TITLE
upload pic error

### ISSUE THREAD

**Issue by bigvaliant** [6ag/jiansan-laravel#9]
web console : POST http://xxxx/admin/upload 500 (Internal Server Error)
laravel log :  local.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\Admin\WallPaperController does not exist' in /var/www/jiansan-laravel/bootstrap/cache/compiled.php:8565
Stack trace:
#0 /var/www/jiansan-laravel/bootstrap/cache/compiled.php(8565): ReflectionMethod->__construct('App\\Http\\Contro...', 'upload')
#1 /var/www/jiansan-laravel/bootstrap/cache/compiled.php(8274): Illuminate\Routing\Route->signatureParameters('Illuminate\\Data...')
#2 /var/www/jiansan-laravel/bootstrap/cache/compiled.php(8268): Illuminate\Routing\Router->substituteImplicitBindings(Object(Illuminate\Routing\Route))
#3 /var/www/jiansan-laravel/bootstrap/cache/compiled.php(8259): Illuminate\Routing\Router->substituteBindings(Object(Illuminate\Routing\Route))
#4 /var/www/jiansan-laravel/bootstrap/cache/compiled.php(8205): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#5 /var/www/jiansan-laravel/bootstrap/cache/compiled.php(8200): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#6 /var/www/jiansan-laravel/bootstrap/cache/compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#7 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#8 /var/www/jiansan-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 /var/www/jiansan-laravel/bootstrap/cache/compiled.php(3286): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /var/www/jiansan-laravel/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/jiansan-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /var/www/jiansan-laravel/vendor/dingo/api/src/Http/Middleware/Request.php(97): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 [internal function]: Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /var/www/jiansan-laravel/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#17 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/jiansan-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/jiansan-laravel/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /var/www/jiansan-laravel/bootstrap/cache/compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /var/www/jiansan-laravel/bootstrap/cache/compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#23 /var/www/jiansan-laravel/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#24 {main}  

How to solve?

**Comment by bigvaliant** [comment]
？
